id: P75F5C228
initial_creation_type: ocr
source_metadata:
  volumes:
    435c1c56552c4eeeb095551dd96d5be3:
      base_file: v016.txt
      image_group_id: I1PD95861
      title: སྒྲོན་མ་གསལ་བར་བྱེད་པའི་དཀའ་བ་བཏུས་པའི་འགྲེལ་པ།
      total_pages: 1354
      volume_number: 16
